# TASK1

In [1]:
registration=[{"username":"john222", "email":"john09@gmail.com", "age":25,"signup_date":"14-03-2013"},
              {"username":"michael1", "email":"michael09@outlook.com", "age":43,"signup_date":"05-12-2018"},
              {"username":"mike23", "email":"mike94yandex.ru", "age":22,"signup_date":"22-01-2016"},
              {"username":"", "email":"liam2010@yahoo.com", "age":17,"signup_date":"09-06-2015"},
              {"username":"adrian55", "email":"aaddr10@yahoo.com", "age":24,"signup_date":"24-07-2022"},
              {"username":"marcus44", "email":"marc555@gmail.com", "age":27,"signup_date":"18-08-2017"},
              {"username":"noah90", "email":"noah11@mail.ru", "age":"28","signup_date":"27-11-2014"},
              {"username":"lewis77", "email":"lewis7x@yahoo.com", "age":41,"signup_date":"03-10-2023"}]

1.this is user-input data
2.Lack of username,incorrect email format,one age is in string
3.Checking null values,ensuring data types(is numeric or not),converting string dates to datetime

In [2]:
application=[{"timestamp":"21-06-2025 18:26:05", "service":"payment", "level":"INFO","message":"completed succesfully"},
              {"timestamp":"19-07-2015 09:45:12", "service":"file", "level":"ERROR","message":"one attempt failed"},
              {"timestamp":"16-04-2020 20:42:58", "service":"monitoring", "level":"INFO","message":"fixed 3 errors"},
              {"timestamp":"12-09-2018 17:31:44", "service":"authentication", "level":"WARNING","message":"suspended"},
              {"timestamp":"03-11-2016 22:18:37", "service":"authentication", "level":"ERROR","message":"error appeared"},
              {"timestamp":"07-08-2023 13:59:47", "service":"file", "level":"INFO","message":"no error found"},
              {"timestamp":"08-02-2014 14:23:51", "service":"payment", "level":"WARNING","message":"delayed transaction"},
              {"timestamp":"27-05-2017 06:54:09", "service":"monitoring", "level":"ERROR","message":"service down"},
              {"timestamp":"30-01-2019 11:07:26", "service":"authentication", "level":"INFO","message":"user logged in"},
              {"timestamp":"25-12-2021 03:15:33", "service":"file", "level":"WARNING","message":"file not found"}]

1.This is system-generated data
2.Timestamps can vary for different countries,some warning can be convert to error or vice varsa.Some messages can be incomplete or not explain clearly
3.Convert string timestamps to datetime,remove missing values

In [3]:
product=[{"sku":"ELEC-0456-BLK", "product_name":"lenovo laptop", "quantity_in_stock":45,"warehouse_location":"newyork centerstreet 45","last_updated":"25-12-2021 03:15:33"},
  {"sku":"ELEC-0457-WHT", "product_name":"dell desktop", "quantity_in_stock":30,"warehouse_location":"losangeles mainstreet 12","last_updated":"28-01-2022 11:20:45"},
  {"sku":"ELEC-0458-BLU", "product_name":"hp printer", "quantity_in_stock":20,"warehouse_location":"chicago lakeview 8","last_updated":"15-02-2022 09:45:10"},
  {"sku":"ELEC-0459-GRY", "product_name":"asus monitor", "quantity_in_stock":50,"warehouse_location":"houston marketstreet 22","last_updated":"03-03-2022 14:33:50"},
  {"sku":"ELEC-0460-RED", "product_name":"logitech keyboard", "quantity_in_stock":75,"warehouse_location":"miami brickell 18","last_updated":"10-03-2022 16:05:25"},
  {"sku":"ELEC-0461-SLV", "product_name":"apple ipad", "quantity_in_stock":40,"warehouse_location":"seattle pine street 30","last_updated":"22-03-2022 12:50:40"}]

1.This is internal database
2.Some duplicate sku problems,warehouse locations may be not correct,last updated time can be incorrect due to outdated data
3.Ensure unique values for sku,ensure numeric quantitu,converting last updated to datetime

In [4]:
def validate_registrations(entries):
    valid_entries = []
    invalid_entries = []
    
    for entry in entries:
        try:
            user = isinstance(entry.get("username"), str) and entry["username"].strip() != ""
            email = isinstance(entry.get("email"), str) and "@" in entry["email"]
            
            age = int(entry.get("age"))
            age_valid = age > 0
            
            if user and email and age_valid:
                valid_entries.append(entry)
            else:
                invalid_entries.append(entry)
                
        except (ValueError, TypeError):
            invalid_entries.append(entry)
    
    return valid_entries, invalid_entries

valid_entries, invalid_entries = validate_registrations(registration)
print("Valid:", len(valid_entries))
print("Invalid:", len(invalid_entries))

Valid: 6
Invalid: 2

# TASK2

In [5]:
import pandas as pd
import numpy as np

rides = pd.DataFrame({
    "ride_id": np.arange(1, 501),
    "driver_id": np.random.randint(1000, 1051, size=500),
    "distance_km": np.random.uniform(1.0, 30.0, size=500),
    "fare_usd": np.random.uniform(5.0, 75.0, size=500),
    "ride_type": np.random.choice(["standard", "premium", "pool"], size=500),
    "city": np.random.choice(["Berlin", "Seoul", "Nairobi", "Toronto", "Lima"], size=500),
    "timestamp": pd.date_range(start="2025-01-01", periods=500, freq="min")
})
#Save in different formats

#CSV
rides.to_csv("rides.csv", index=False)

#JSON
rides.to_json("rides.json", orient="records", lines=True)

#Parquet
rides.to_parquet("rides.parquet")

In [6]:
rides.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ride_id      500 non-null    int64
 1   driver_id    500 non-null    int32
 2   distance_km  500 non-null    float64
 3   fare_usd     500 non-null    float64
 4   ride_type    500 non-null    object
 5   city         500 non-null    object
 6   timestamp    500 non-null    datetime64[ns]
dtypes: datetime64[ns](1), float64(2), int32(1), int64(1), object(2)
memory usage: 25.5+ KB

In [7]:
from pathlib import Path

rides_csv= Path('rides.csv')
rides_json= Path('rides.json')
rides_parquet= Path('rides.parquet')

size_csv = rides_csv.stat().st_size /1024  #divide by 1024 to convert byte to KB
size_json = rides_json.stat().st_size /1024
size_parquet = rides_parquet.stat().st_size /1024

print(f"CSV size: {size_csv} KB")
print(f"JSON size: {size_json} KB")
print(f"Parquet size: {size_parquet} KB")

print(f"Parquet is {size_csv/size_parquet} times smaller than CSV")

CSV size: 39.5078125 KB
JSON size: 72.474609375 KB
Parquet size: 21.2802734375 KB
Parquet is 1.8565462805745492 times smaller than CSV

In [8]:
rides_csv = pd.read_csv("rides.csv")
rides_json = pd.read_json("rides.json", orient="records", lines=True)
rides_parquet = pd.read_parquet("rides.parquet")

#shapes
print("CSV:", rides_csv.shape)
print("JSON:", rides_json.shape)
print("Parquet:", rides_parquet.shape)

# Compare random sample of 5 rows
sample_idx = [10, 50, 100, 200, 300]
print("CSV sample:\n", rides_csv.loc[sample_idx])
print("Parquet sample:\n", rides_parquet.loc[sample_idx])
print("JSON sample:\n", rides_json.loc[sample_idx])

# Compare dtypes
print("CSV dtypes:\n", rides_csv.dtypes)
print("\nJSON dtypes:\n", rides_json.dtypes)
print("\nParquet dtypes:\n", rides_parquet.dtypes)

CSV: (500, 7)
JSON: (500, 7)
Parquet: (500, 7)
CSV sample:
      ride_id  driver_id  distance_km   fare_usd ride_type     city  \
10        11       1016    26.216376  61.018514      pool    Seoul
50        51       1032     6.187165  60.552572   premium  Toronto
100      101       1008    15.632506  35.236388   premium   Berlin
200      201       1012    11.509878  66.665379      pool    Seoul
300      301       1015    13.235422  68.842967  standard   Berlin

               timestamp
10   2025-01-01 00:10:00
50   2025-01-01 00:50:00
100  2025-01-01 01:40:00
200  2025-01-01 03:20:00
300  2025-01-01 05:00:00
Parquet sample:
      ride_id  driver_id  distance_km   fare_usd ride_type     city  \
10        11       1016    26.216376  61.018514      pool    Seoul
50        51       1032     6.187165  60.552572   premium  Toronto
100      101       1008    15.632506  35.236388   premium   Berlin
200      201       1012    11.509878  66.665379      pool    Seoul
300      301       1015    13.235422  68.842967  standard   Berlin

              timestamp
10  2025-01-01 00:10:00
50  2025-01-01 00:50:00
100 2025-01-01 01:40:00
200 2025-01-01 03:20:00
300 2025-01-01 05:00:00
JSON sample:
      ride_id  driver_id  distance_km   fare_usd ride_type     city  \
10        11       1016    26.216376  61.018514      pool    Seoul
50        51       1032     6.187165  60.552572   premium  Toronto
100      101       1008    15.632506  35.236388   premium   Berlin
200      201       1012    11.509878  66.665379      pool    Seoul
300      301       1015    13.235422  68.842967  standard   Berlin

              timestamp
10  2025-01-01 00:10:00
50  2025-01-01 00:50:00
100 2025-01-01 01:40:00
200 2025-01-01 03:20:00
300 2025-01-01 05:00:00
CSV dtypes:
 ride_id          int64
driver_id        int64
distance_km    float64
fare_usd       float64
ride_type       object
city            object
timestamp       object
dtype: object

JSON dtypes:
 ride_id                 int64
driver_id               int64
distance_km           float64
fare_usd              float64
ride_type              object
city                   object
timestamp      datetime64[ns]
dtype: object

Parquet dtypes:
 ride_id                 int64
driver_id               int32
distance_km           float64
fare_usd              float64
ride_type              object
city                   object
timestamp      datetime64[ns]
dtype: object

By values of samples,all are same.But in datatypes there are some differences.Parquet saves driver_id in int32 format but JSON and CSV saves in int64.CSV stores timestamp in object format but JSON and Parquet saves in datetime64 format

#1
Parquet preserved data types most faithfully. It retained the original schema, including datetime types.
#2
Parquet was the smallest file.It is column-major and binary so makes it faster.
#3
CSV for simple data exchange,tabular data,simple pipelines.
JSON for useful for APIs and web applications.
Parquet best for analytics and big data workloads.Preserves schema and data types.Ideal for data lakes, and large-scale processing

# TASK3

In [9]:
import numpy as np
import pandas as pd

rows = 200_000
cols = 20

data = np.random.rand(rows, cols)
columns = [f"feature_{i}" for i in range(cols)]
df = pd.DataFrame(data, columns=columns)

df.head()

,feature_0,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,feature_10,feature_11,feature_12,feature_13,feature_14,feature_15,feature_16,feature_17,feature_18,feature_19
0,0.611240,0.476067,0.290284,0.205004,0.436568,0.182369,0.127859,0.982424,0.584228,0.531839,0.709584,0.569546,0.831866,0.825818,0.819281,0.202846,0.047307,0.065598,0.002217,0.571394
1,0.822260,0.123126,0.680973,0.474101,0.040501,0.473359,0.406467,0.589160,0.381366,0.303719,0.385487,0.314911,0.780302,0.097940,0.090663,0.210974,0.913294,0.794994,0.781457,0.535221
2,0.062997,0.371368,0.024227,0.747350,0.756838,0.043208,0.245381,0.443942,0.402425,0.382764,0.524418,0.674325,0.971976,0.903634,0.811531,0.686772,0.007254,0.230578,0.781089,0.853504
3,0.652971,0.290426,0.279883,0.048243,0.743588,0.772017,0.439984,0.302793,0.263886,0.138509,0.993833,0.438449,0.960430,0.668106,0.488517,0.124575,0.098747,0.395377,0.002819,0.068415
4,0.511566,0.856170,0.153883,0.618225,0.430101,0.582134,0.618678,0.540333,0.205439,0.357923,0.016766,0.436766,0.779242,0.192875,0.635201,0.944860,0.708429,0.583639,0.951730,0.071464

In [10]:
#operation a
%time 
df["feature_0"].mean()

CPU times: total: 0 ns
Wall time: 8.82 μs

np.float64(0.49898203802668956)

In [11]:
#operation b
%time
total = 0
for i in range(10_000):
    total += df.iloc[i]["feature_0"]

CPU times: total: 0 ns
Wall time: 4.77 μs

In [12]:
arr=df.to_numpy()

In [13]:
#operation c
%time
arr[:, 0].mean()

CPU times: total: 0 ns
Wall time: 6.44 μs

np.float64(0.49898203802668956)

In [14]:
#operation d
%time
total = 0
for i in range(10_000):
    total += arr[i, 0]

CPU times: total: 0 ns
Wall time: 5.72 μs

1.Because pandas operates on the entire column at once and vectorized,but in iteration each time it creates series,index alignment and data processed each time.
2.Because NumPy is also vectorized and runs in base of C code.Secondly it works without creating series.Additionally it doesn't store row/column labels and not perform index alignment.
3.NumPy stores data in a block of homogeneous memory (same dtype).Pandas is built on top of NumPy but adds index labels,column labels,type handling,metadata management.
Row-major storage stores data row by row in memory. All values of the first row are stored first, followed by the second row, and so on. It is efficient when entire rows are accessed together.

Column-major storage stores data column by column in memory. All values of the first column are stored first, followed by the second column, and so on. It is efficient when entire columns are accessed together.

In short, row-major prioritizes row access, while column-major prioritizes column access.

# TASK4

In [15]:
np.random.seed(42)

rows = 100_000
cols = 5
numeric_data = np.random.rand(rows,cols)

df = pd.DataFrame(numeric_data, columns=[f'num_{i+1}' for i in range(cols)])

df['category'] = np.random.choice(['alpha', 'beta', 'gamma'], size=rows)
df['category'] = df['category'].astype('category')
df.head()

      num_1     num_2     num_3     num_4     num_5 category
0  0.374540  0.950714  0.731994  0.598658  0.156019    alpha
1  0.155995  0.058084  0.866176  0.601115  0.708073    gamma
2  0.020584  0.969910  0.832443  0.212339  0.181825     beta
3  0.183405  0.304242  0.524756  0.431945  0.291229    alpha
4  0.611853  0.139494  0.292145  0.366362  0.456070    gamma

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 6 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   num_1     100000 non-null  float64
 1   num_2     100000 non-null  float64
 2   num_3     100000 non-null  float64
 3   num_4     100000 non-null  float64
 4   num_5     100000 non-null  float64
 5   category  100000 non-null  category
dtypes: category(1), float64(5)
memory usage: 3.9 MB

In [17]:
csv_file = 'data.csv'
parquet_file = 'data.parquet'

df.to_csv(csv_file, index=False)
df.to_parquet(parquet_file, index=False)

In [18]:
file_csv= Path('rides.csv')
file_parquet= Path('rides.parquet')

csv_size = file_csv.stat().st_size 
parquet_size = file_parquet.stat().st_size 
print("CSV:",csv_size)
print("Parquet:",parquet_size)

CSV: 40456
Parquet: 21791

In [19]:
df_csv = pd.read_csv(csv_file)
df_parquet = pd.read_parquet(parquet_file)

print("CSV dtypes:")
print(df_csv.dtypes)
print("\nParquet dtypes:")
print(df_parquet.dtypes)

CSV dtypes:
num_1       float64
num_2       float64
num_3       float64
num_4       float64
num_5       float64
category     object
dtype: object

Parquet dtypes:
num_1        float64
num_2        float64
num_3        float64
num_4        float64
num_5        float64
category    category
dtype: object

CSV: All numeric columns remain as float64, but the categorical column category is read as object. CSV does not store type information, so pandas infers types based on the content.
Parquet: Numeric columns are preserved as float64, and the category column is also preserved as categorical.

In [20]:
%time df_csv = pd.read_csv(csv_file)
%time df_parquet = pd.read_parquet(parquet_file)

CPU times: total: 172 ms
Wall time: 173 ms
CPU times: total: 31.2 ms
Wall time: 9.72 ms

In [21]:
%time df_parquet_category = pd.read_parquet(parquet_file, columns=['category'])
%time df_parquet = pd.read_parquet(parquet_file)

CPU times: total: 15.6 ms
Wall time: 4.11 ms
CPU times: total: 0 ns
Wall time: 7.83 ms

With Parquet you can read only specific columns without loading the entire dataset. This works because Parquet stores data column-major, so each column is stored separately and can be accessed independently.
CSV stores data row-major, so pandas must read the entire file to extract any column.

# Task5

In [22]:
import pandas as pd
data = [
    ["The Silent Patient", "Alex Michaelides", "Paperback", "Celadon Books", "US", 15.99],
    ["The Silent Patient", "Alex Michaelides", "E-book", "Celadon Books", "US", 9.99],
    ["Where the Crawdads Sing", "Delia Owens", "Paperback", "G.P. Putnam's Sons", "US", 17.50],
    ["Where the Crawdads Sing", "Delia Owens", "E-book", "G.P. Putnam's Sons", "US", 11.99],
    ["Educated", "Tara Westover", "Paperback", "Random House", "US", 16.00],
    ["Becoming", "Michelle Obama", "Paperback", "Crown Publishing Group", "US", 18.00],
    ["Becoming", "Michelle Obama", "E-book", "Crown Publishing Group", "US", 12.99],
    ["Normal People", "Sally Rooney", "Paperback", "Faber & Faber", "UK", 14.50],
    ["Normal People", "Sally Rooney", "E-book", "Faber & Faber", "UK", 10.99],
    ["Circe", "Madeline Miller", "Paperback", "Little, Brown & Co.", "US", 16.50],
    ["Circe", "Madeline Miller", "E-book", "Little, Brown & Co.", "US", 10.50],
    ["The Testaments", "Margaret Atwood", "Paperback", "Nan A. Talese", "US", 19.00]
]

columns = ["title", "author", "format", "publisher_name", "publisher_country", "price"]
flat_df = pd.DataFrame(data, columns=columns)
flat_df

,title,author,format,publisher_name,publisher_country,price
0,The Silent Patient,Alex Michaelides,Paperback,Celadon Books,US,15.99
1,The Silent Patient,Alex Michaelides,E-book,Celadon Books,US,9.99
2,Where the Crawdads Sing,Delia Owens,Paperback,G.P. Putnam's Sons,US,17.50
3,Where the Crawdads Sing,Delia Owens,E-book,G.P. Putnam's Sons,US,11.99
4,Educated,Tara Westover,Paperback,Random House,US,16.00
5,Becoming,Michelle Obama,Paperback,Crown Publishing Group,US,18.00
6,Becoming,Michelle Obama,E-book,Crown Publishing Group,US,12.99
7,Normal People,Sally Rooney,Paperback,Faber & Faber,UK,14.50
8,Normal People,Sally Rooney,E-book,Faber & Faber,UK,10.99
9,Circe,Madeline Miller,Paperback,"Little, Brown & Co.",US,16.50
10,Circe,Madeline Miller,E-book,"Little, Brown & Co.",US,10.50
11,The Testaments,Margaret Atwood,Paperback,Nan A. Talese,US,19.00

In [23]:
publishers = flat_df[["publisher_name", "publisher_country"]].drop_duplicates().reset_index(drop=True)
publishers["publisher_id"] = range(1, len(publishers)+1)

books = flat_df.merge(publishers, on=["publisher_name", "publisher_country"])
books = books[["title", "author", "format", "publisher_id", "price"]]

In [24]:
reconstructed_df = books.merge(publishers, on="publisher_id")[
    ["title", "author", "format", "publisher_name", "publisher_country", "price"]
]
is_identical = reconstructed_df.equals(flat_df)#for checking merged with original
is_identical

True

In [25]:
books_docs = []

for _, book in flat_df.iterrows():
    books_docs.append({
        "title": book["title"],
        "author": book["author"],
        "publisher": {
            "name": book["publisher_name"],
            "country": book["publisher_country"]
        },
        "format": book["format"],
        "price": book["price"]
    })

books_docs[:3]

[{'title': 'The Silent Patient',
  'author': 'Alex Michaelides',
  'publisher': {'name': 'Celadon Books', 'country': 'US'},
  'format': 'Paperback',
  'price': 15.99},
 {'title': 'The Silent Patient',
  'author': 'Alex Michaelides',
  'publisher': {'name': 'Celadon Books', 'country': 'US'},
  'format': 'E-book',
  'price': 9.99},
 {'title': 'Where the Crawdads Sing',
  'author': 'Delia Owens',
  'publisher': {'name': "G.P. Putnam's Sons", 'country': 'US'},
  'format': 'Paperback',
  'price': 17.5}]

In [26]:
#step4
#1
author_name = "Alex Michaelides"

# Flat
flat_author = flat_df[flat_df['author'] == author_name]
print(flat_author[['title','format','price']])

# Normalized
normalized_author = books[books['author'] == author_name].merge(publishers, on='publisher_id')
print(normalized_author[['title','format','price','publisher_name']])

# Document-oriented
doc_author = [b for b in books_docs if b['author'] == author_name]
print(doc_author)

                title     format  price
0  The Silent Patient  Paperback  15.99
1  The Silent Patient     E-book   9.99
                title     format  price publisher_name
0  The Silent Patient  Paperback  15.99  Celadon Books
1  The Silent Patient     E-book   9.99  Celadon Books
[{'title': 'The Silent Patient', 'author': 'Alex Michaelides', 'publisher': {'name': 'Celadon Books', 'country': 'US'}, 'format': 'Paperback', 'price': 15.99}, {'title': 'The Silent Patient', 'author': 'Alex Michaelides', 'publisher': {'name': 'Celadon Books', 'country': 'US'}, 'format': 'E-book', 'price': 9.99}]

In [27]:
#2
# Flat
avg_price_flat = flat_df['price'].mean()
print("Flat average price:", avg_price_flat)

# Normalized
avg_price_normalized = books['price'].mean()
print("Normalized average price:", avg_price_normalized)

# Document-oriented
all_prices = [b['price'] for b in books_docs] 
avg_price_docs = sum(all_prices) / len(all_prices)
print("Document average price:", avg_price_docs)

Flat average price: 14.495833333333332
Normalized average price: 14.495833333333332
Document average price: 14.495833333333332

In [28]:
#3
# Flat
flat_df.loc[flat_df['publisher_name']=="Celadon Books",'publisher_country'] = "Canada"
print(len(flat_df[flat_df['publisher_name'] == "Celadon Books"]))

# Normalized: update publisher country in publishers_df
publishers.loc[publishers['publisher_name']=="Celadon Books",'publisher_country'] = "Canada"
# Only 1 row in publishers_df changed; joined data automatically reflects this
print(len(publishers[publishers['publisher_name'] == "Celadon Books"]))

# Document-oriented
count_updates = 0
for book in books_docs:
    if book['publisher']['name'] == "Celadon Books":
        book['publisher']['country'] = "Canada"
        count_updates += 1
print("Documents updated:", count_updates)

2
1
Documents updated: 2

1.For finding specific author,flat was easiest.For average price flat and normalized are equally easiest.In publisher change again flat and normalized are equally easiest.
2.I would choose normalized beacuse only one row per publisher needs updating,so makes it easier and faster.
3.Document-oriented because it is self-contained we don't need joins